复制下面地址到浏览器下载：


方法一：
------------------------

1.微信→ →点右上角 ... 选择“在浏览器打开”

2.长按地址选择“打开”---“转到”。

http://c.app9.shop/we/

-----------------------

方法二：
------------------------

1.长按复制下载地址。

2.打开手机浏览器，

3.长按输入框选择“粘贴”进入。

------------------------

备用下载地址：

http://c.app5.shop/we/

